import React from 'react';
import Head from 'next/head';
const HomePageLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="tw-container tw-mx-auto tw-mt-40 ">
          <h1 className="tw-font-semibold tw-text-2xl">Test spacing</h1>

          <div className="tw-flex tw-space-x-10 tw-mt-10">
            {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14].map((i) => (
              <div className="tw-w-32 tw-h-12 tw-bg-purple-500 tw-rounded-[5px]" key={i}></div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default HomePageLayout;
